Repository ultralytics/mkdocs, pull requests merged in 2024-10, with the labels that each got.

#101 Ultralytics Code Refactor https://ultralytics.com/actions
  README.md
Labels: enhancement

#102 Ultralytics Code Refactor https://ultralytics.com/actions
  README.md
Labels: documentation, enhancement

#103 Update publish.yml to trusted publisher
  .github/workflows/publish.yml
  pyproject.toml
Labels: dependencies, enhancement

#104 Ultralytics Code Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
  .github/workflows/publish.yml
Labels: enhancement

#105 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#107 Lazy load avatar images
  plugin/main.py
  pyproject.toml
Labels: enhancement

#108 Python 3.13 update
  pyproject.toml
Labels: dependencies
