Repository ultralytics/mkdocs, pull requests merged in 2024-08, with the labels that each got.

#72 Add smart dates and authors
  README.md
  plugin/main.py
  plugin/utils.py
  pyproject.toml
Labels: documentation, enhancement

#73 Refactor code
  .github/workflows/publish.yml
  plugin/main.py
  plugin/utils.py
Labels: enhancement

#74 Update CSS handling
  README.md
  plugin/main.py
  pyproject.toml
Labels: enhancement

#75 0.1.1
  pyproject.toml
Labels: dependencies, enhancement

#76 Fix missing author profiles
  plugin/main.py
  pyproject.toml
Labels: documentation, enhancement

#77 Adjust for mobile
  plugin/main.py
  pyproject.toml
Labels: documentation, enhancement

#79 Update
  plugin/main.py
Labels: documentation, enhancement

#78 Update Twitter to X icon
  plugin/main.py
  pyproject.toml
Labels: documentation, enhancement

#80 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: dependencies, documentation, enhancement

#81 Update publish.yml
  .github/workflows/publish.yml
  pyproject.toml
Labels: dependencies, enhancement

#82 Fix repo in pip publish action
  .github/workflows/publish.yml
  pyproject.toml
Labels: enhancement

#83 Update publish.yml to GPT4o-08-06
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#85 Add https://www.reddit.com/r/Ultralytics/ badge
  README.md
  plugin/utils.py
Labels: documentation, enhancement

#87 Optimize avatar sizes
  plugin/main.py
  plugin/utils.py
  pyproject.toml
Labels: documentation, enhancement

#88 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#93 Update pyproject.toml to v0.1.8
  pyproject.toml
Labels: dependencies, enhancement
