Repository ultralytics/mkdocs, pull requests merged in 2025-08, with the labels that each got.

#145 Fix author profile image links
  plugin/__init__.py
  plugin/main.py
Labels: dependencies, documentation

#147 Add automated SPDX SBOM generation to releases
  .github/workflows/publish.yml
  plugin/__init__.py
Labels: dependencies, enhancement, devops

#148 SBOM uv sync fix
  .github/workflows/publish.yml
Labels: dependencies, enhancement, devops

#150 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, devops

#151 Ultralytics Refactor https://ultralytics.com/actions
  README.md
Labels: documentation
