Repository ultralytics/mkdocs, pull requests merged in 2025-01, with the labels that each got.

#120 Update format.yml
  .github/workflows/format.yml
Labels: enhancement, devops

#121 Fix format.yml spacing
  .github/workflows/format.yml
Labels: documentation, devops

#122 Apply `ruff==0.9.0` formatting
  plugin/main.py
Labels: enhancement, devops

#123 Standardize license headers in Python files
  plugin/__init__.py
  plugin/main.py
  plugin/utils.py
Labels: documentation

#124 Standardize license headers in TOML/YAML files
  .github/dependabot.yml
  .github/workflows/format.yml
  .github/workflows/publish.yml
  pyproject.toml
Labels: documentation

#125 Add default author feature
  .gitignore
  README.md
  plugin/main.py
  plugin/utils.py
  pyproject.toml
Labels: documentation, enhancement
